SONG_TITLES = [

    "Midnight Dreams",
    "Broken Sky",
    "Golden Rain",
    "Echoes",
    "Fire Within",
    "Lost Again",
    "Sunrise Melody",
    "Dancing Lights",
    "Forever Mine",
    "Lonely Road",
    "Ocean Waves",
    "Silent Voice",
    "Moonlight",
    "Heartbeat",
    "Magic Night",
    "Beautiful Soul",
    "Stay With Me",
    "Higher",
    "Dream On",
    "Infinity",
    "Wild Fire",
    "Blue Horizon",
    "Morning Breeze",
    "Shining Star",
    "Electric Love",
    "Gravity",
    "Paradise",
    "Cloud Nine",
    "After Rain",
    "Freedom",

    "Sky High",
    "Golden Heart",
    "Hope",
    "New World",
    "Lost Paradise",
    "Snowfall",
    "Mirage",
    "Wonderland",
    "One More Time",
    "Into The Night",
    "Endless Love",
    "Closer",
    "Memories",
    "Alive",
    "Stronger",
    "Phoenix",
    "Universe",
    "Spark",
    "Heartbeat Again",
    "Tomorrow"

]